<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ConectaSuporte\ConectaSuporte.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\ia\**\*" LinkBase="ia" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
